[package]
name = "quote-bot"
version = "0.1.0"
authors = ["Navrin <navman360@gmail.com>"]

[dependencies]
clippy = {version = "*", optional = true}

[dependencies.serenity]
git = "https://github.com/zeyla/serenity"
branch = "v0.5.0"