(function() {var implementors = {};
implementors["quote_bot"] = ["impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/authors/struct.id.html\" title=\"struct quote_bot::db::schema::authors::id\">id</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/authors/struct.table.html\" title=\"struct quote_bot::db::schema::authors::table\">table</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/quotes/struct.id.html\" title=\"struct quote_bot::db::schema::quotes::id\">id</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/quotes/struct.message_id.html\" title=\"struct quote_bot::db::schema::quotes::message_id\">message_id</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/quotes/struct.quote.html\" title=\"struct quote_bot::db::schema::quotes::quote\">quote</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/quotes/struct.created_by_id.html\" title=\"struct quote_bot::db::schema::quotes::created_by_id\">created_by_id</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/quotes/struct.quoted_by_id.html\" title=\"struct quote_bot::db::schema::quotes::quoted_by_id\">quoted_by_id</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/quotes/struct.guild_id.html\" title=\"struct quote_bot::db::schema::quotes::guild_id\">guild_id</a>","impl <a class=\"trait\" href=\"diesel/query_builder/query_id/trait.QueryId.html\" title=\"trait diesel::query_builder::query_id::QueryId\">QueryId</a> for <a class=\"struct\" href=\"quote_bot/db/schema/quotes/struct.table.html\" title=\"struct quote_bot::db::schema::quotes::table\">table</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
